library identifier: 'JenkinsTest@main',
        retriever: modernSCM([$class: 'GitSCMSource',
        remote: 'https://github.com/pawel02/JenkinsTest.git'])

pipeline {
    agent any
    //triggers { pollSCM ('H/15 * * * *') }
    parameters{
        booleanParam(name: 'RC', defaultValue: false, description: 'Is it a release candidate?')
    }
    environment{
        VERSION = "0.1.0"
        VERSION_RC = "rc.2"
    }
    stages {
        stage('Preperation') {
            environment
            {
                VERSION_SUFFIX = getVersionSuffix()
            }
            steps {
                suffix()
                echo "Preparing the build ${VERSION_SUFFIX}"
                git url: 'https://github.com/pawel02/JenkinsTest.git', branch: "main"
                bat 'npm install'
            }
        }
        stage('Test')
        {
            steps
            {
                bat 'ng test --reporters=junit --watch=false'
            }   
            post {
                //record the test results
                always {
                    junit 'coverage-test/testFile.xml'
                }
                changed{
                    emailext attachLog: true,
                     body: 'please go to ${BUILD_URL} and verify build', 
                     compressLog: true,
                      recipientProviders: [upstreamDevelopers()], 
                      subject: 'JOB \'${JOB_NAME}\' (${BUILD_NUMBER}) is waiting for input', 
                      to: 'pawel.bes12@gamail.com'                
                }
            }
        }
        stage('Build')
        {
            when{
                expression { return params.RC }
            }
            steps
            {
                bat 'ng build --prod'
                archiveArtifacts('dist/')
            }   
        }
        
    }
}

String getVersionSuffix()
{
    if(params.RC)
    {
        return env.VERSION_RC
    }
    else
    {
        return env.VERSION_RC + '+ci.' + env.BUILD_NUMBER
    }
}