pipeline {
    agent any
    triggers { pollSCM ('* * * * *') }
    stages {
        stage('Preperation') {
            steps {
                git url: 'https://github.com/pawel02/JenkinsTest.git', branch: "main"
                bat 'npm install'
            }
        }
        stage('Test')
        {
            steps
            {
                bat 'ng test --reporters=junit --watch=false'
            }   
            post {
                //record the test results
                always {
                    junit 'coverage-test/testFile.xml'
                }
                changed{
                    emailext attachLog: true,
                     body: 'please go to ${BUILD_URL} and verify build', 
                     compressLog: true,
                      recipientProviders: [upstreamDevelopers()], 
                      subject: 'JOB \'${JOB_NAME}\' (${BUILD_NUMBER}) is waiting for input', 
                      to: 'pawel.bes12@gamail.com'                
                }
            }
        }
        stage('Build')
        {
            steps
            {
                bat 'ng build --prod'
            }   
        }
        
    }
}